version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 392129347642.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-docker-image .

  post_build:
    commands:
      - echo Tagging Docker image...
      - docker tag myecrrepo:latest 392129347642.dkr.ecr.us-east-1.amazonaws.com/myecrrepo:latest
      - echo Pushing Docker image to Amazon ECR...
      - docker push 392129347642.dkr.ecr.us-east-1.amazonaws.com/myecrrepo:latestt
